# paginate    : 5

# No baseurl needed for gulp
# baseurl     : ""

# Show drafts and future posts?
future      : false
show_drafts : false

# Gives you more accurate related posts
lsi         : false

# Max posts to render
# limit_posts : 20
