# Site settings
title         : EdgePoint Learning
description   : ommitted to designing, developing and delivering blended learning solutions that drive organizational performance and business value while enriching the capabilities of working adults, EdgePoint Enables.
tagline       : Innovative Learning Solutions for Better Business Results
url           : 'http://edgepointlearning.github.io'
baseurl       : '' #/epl-optimized

# Color variable for Android & Windows tiles
color         : '#12519E'
blog_image_dir: '/assets/images/blog/'

# Permalinks
permalink     : pretty
paginate      : 7
paginate_path : '/blog/page:num'

# Filtering Content
future        : false
show_drafts   : false
limit_posts   : 0
lsi           : false

# Include
include       : ['_pages', '_demos']

# Sass
sass          :
  sass_dir    : assets/sass
  style       : compressed

# Collections
collections   :
  boxes       :
    output    : false
  solutions   :
    output    : false

defaults      :
  -
    scope     :
      path    : "" # an empty string here means all files in the project
    values    :
      layout  : "default"
  -
    scope     :
      path    : ""
      type    : "posts" # the fables collection
    values    :
      layout  : "post" # will default to the fable layout

# Exclude
exclude       : [bower_components, node_modules, gulpfile.js, package.json]
