# Site settings
title         : EdgePoint Learning
description   : Committed to designing, developing and delivering blended learning solutions that drive organizational performance and business value while enriching the capabilities of working adults, EdgePoint Enables.
tagline       : Innovative Learning Solutions for Better Business Results
url           : 'http://edgepointlearning.github.io'
baseurl       : '' #/epl-optimized

# Color variable for Android & Windows tiles
color         : 'RGB(18, 82, 158)'
blog_image_dir: '/assets/images/blog/'

# Permalinks
permalink     : pretty
paginate      : 7
paginate_path : '/blog/page:num'

# Filtering Content
future        : false
show_drafts   : false
limit_posts   : 0
lsi           : false

# Pagination
gems:
  - jekyll-paginate

# Include
include       : ['_pages']

# Sass
sass          :
  sass_dir    : assets/sass
  style       : compressed

# Collections
collections   :
  case_studies:
    output    : false
  forms       :
    output    : false


defaults      :
  -
    scope     :
      path    : "" # an empty string here means all files in the project
    values    :
      layout  : "default"
      boxes:
       - talk
       - solutions
       - demos
       - newsletter
  -
    scope     :
      path    : ""
      type    : "posts" # the post collection
    values    :
      layout  : "post" # will default to the post layout
      boxes   :
       - talk
       - newsletter

# Exclude
exclude       : [bower_components, node_modules, gulpfile.js, package.json, npm-shrinkwrap.json]
