# Site settings
title        : EdgePoint Learning
description  : Committed to designing, developing and delivering blended learning solutions that drive organizational performance and business value while enriching the capabilities of working adults, EdgePoint Enables.
tagline      : Innovative Learning Solutions for Better Business Results
url          : 'http://edgepointlearning.github.io'
baseurl      : '' #/epl-optimized

# Color variable for Android & Windows tiles
color        : 'RGB(18, 82, 158)'
image_dir    : '/assets/images/blog/'

# Nav
navItems:
  - url: /solutions/
    title: <span>Learning </span>Solutions
  - url: /stories/
    title: <span>Success </span>Stories
  - url: /blog/
    title: Blog
  - url: /about/
    title: About
  - url: /contact/
    title: Contact

# Permalinks
permalink    : pretty

# Filtering Content
future       : false
show_drafts  : false
limit_posts  : 0
lsi          : false
excerpt_separator: <!--more-->

# Include
include      : ['_pages']

# Sass
sass         :
  sass_dir   : assets/sass
  style      : compressed

# Collections
collections  :
  stories    :
    output   : false
  forms      :
    output   : true


defaults     :
  -
    scope    :
      path   : "" # an empty string here means all files in the project
    values   :
      layout : "page"
      cards  :
       - talk
       - solutions
       - demos
       - newsletter
  -
    scope    :
      type   : "posts" # the post collection
    values   :
      layout : "post" # will default to the post layout
      cards  :
       - talk
       - newsletter
  -
    scope    :
      type   : "stories"
    values   :
      layout : "page"
      cards  :
       - demos
       - talk
  -
    scope:
      path: ""
      type: forms
    values:
      layout: default

# Exclude
exclude      : [bower_components, node_modules, bower.json, gulpfile.js, npm-shrinkwrap.json, package.json]
