# SEO
title      : EdgePoint Learning
description: "From microlearning to blended learning opportunities, EdgePoint Learning designs eLearning solutions for today's employees."
keywords   : "EdgePoint Learning, eLearning, eLearning development company, custom eLearning, custom eLearning solutions, employee training, corporate compliance training, microlearning"
color      : '#12529e'
url        : 'https://www.edgepointlearning.com'
baseurl    : '' # '/example'

# Plugins & Settings
plugins :
  - jekyll-paginate-v2
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap

livereload : true

pagination : # https://github.com/sverrirs/jekyll-paginate-v2
  enabled  : true
autopages  : # https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md
  enabled  : false

assets         :  # https://github.com/envygeeks/jekyll-assets/tree/v2.4.0
  autoprefixer :
    browsers   :
      - 'last 2 versions'
      - 'ie >= 9'
      - 'Android >= 2.3'
      - 'ios >= 7'
  digest       : false # TEMPORARY FIX FOR FACEBOOK & TWITTER CARDS
  # cache      : false # TEMPORARILY FIXES FONT CACHING BUG
  features     :
    automatic_img_size: false

# Includes & Excludes
include :
  - _pages
  - _redirects
  - _headers

exclude :
  - .asset-cache
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - netlify.toml
  - docker-compose.yml

# Collections
collections_dir: collections
collections   :
  stories     :
    output    : true
    permalink : /story/:path/
  forms       :
    output    : true
    permalink : /form/:path/
  demos       :
    output    : true
    permalink : /demo/:path/
  solutions   :
    output    : true
    permalink : /:path/

# Defaults
defaults :
  -
    scope       :
      path      : '' # an empty string here means all files in the project
    values      :
      layout    : 'page'
      cards     :
       - talk
       - solutions
       - demos
       - newsletter
  -
    scope       :
      type      : 'posts' # the post collection
    values      :
      layout    : 'post' # will default to the post layout
      permalink : /blog/:title/
      blog      : true
      cards     :
       - talk
       - newsletter
  -
    scope       :
      type      : 'solutions'
    values      :
      layout    : 'solution'
      solution  : true
  -
    scope       :
      type      : 'stories'
    values      :
      layout    : 'story'
      story     : true
      last_modified_at: 2018-06-01T00:00:00-07:00
      cards     :
       - demos
       - talk
  -
    scope       :
      type      : forms
    values      :
      layout    : 'form'
      noindex   : true
      sitemap   : false
      cards     : no
  -
    scope       :
      type      : demos
    values      :
      layout    : 'demo'
      noindex   : true
      sitemap   : false
      cards     :
       - solutions
       - newsletter
  -
    scope       :
      path      : 'static/**/*.pdf'
    values      :
      sitemap   : false
