# Site settings
title        : EdgePoint Learning
description  : Committed to designing, developing and delivering blended learning solutions that drive organizational performance and business value, EdgePoint Enables.
keywords     : elearning, instructor-led, training, edgepoint learning, edgepoint, edge point, edge point learning, instructional design metrics, edgepoint training
url          : 'https://www.edgepointlearning.com'
baseurl      : ''

# Color variable for Android & Windows tiles
color        : 'RGB(18, 82, 158)'
image_dir    : '/assets/images/blog/'

# Nav
navItems:
  - url: /solutions/
    title: <span>Learning </span>Solutions
  - url: /stories/
    title: <span>Success </span>Stories
  - url: /blog/
    title: Blog
  - url: /about/
    title: About
  - url: /contact/
    title: Contact

# Permalinks
# permalink    : pretty

# Filtering Content
future       : false
show_drafts  : false
limit_posts  : 0
lsi          : false
excerpt_separator: <!--more-->

# Sass
sass         :
 sass_dir   : assets/sass
 style      : compressed

# Collections
collections  :
  stories    :
    output   : true
    permalink: /story/:path/
  forms      :
    output   : true
    permalink: /form/:path/
  demos      :
    output   : false
  demo-bundles:
    output   : true
    permalink: /sample/:path/

defaults     :
  -
    scope    :
      path   : '' # an empty string here means all files in the project
    values   :
      layout : 'page'
      cards  :
       - talk
       - solutions
       - demos
       - newsletter
  -
    scope    :
      type   : 'posts' # the post collection
    values   :
      layout : 'post' # will default to the post layout
      permalink: /blog/:title/
      cards  :
       - talk
       - newsletter
  -
    scope    :
      type   : 'stories'
    values   :
      layout : 'story'
      cards  :
       - demos
       - talk
  -
    scope    :
      type   : forms
    values   :
      layout : 'form'
      cards  : no
      sitemap: false
  -
    scope     :
      path    : "_demo-bundles"
    values    :
      layout  : "sampler"
      sitemap: false
      cards  :
       - sampler

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

livereload: true

include :
  - _pages
  - _headers #netlify

exclude :
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - netlify.toml
  - docker-compose.yml
  - .ruby-version
