# production: this context corresponds to the main site’s deployment, attached to the Git branch you set when the site is created.
[context.production]
  command = "jekyll build --config _config.yml,_config.staging.yml"
  [context.production.environment]
    JEKYLL_ENV = "staging"

# deploy-preview: this context corresponds to the previews we build for Pull Requests and Merge Requests integrations.
[context.deploy-preview]
  command = "jekyll build --config _config.yml,_config.staging.yml"
  [context.deploy-preview.environment]
    JEKYLL_ENV = "staging"

# branch-deploy: this context corresponds to deploys from branches that are not the site’s main production branch.
[context.branch-deploy]
  command = "jekyll build --config _config.yml,_config.staging.yml --future“
  [context.branch-deploy.environment]
    JEKYLL_ENV = "staging"
