# production: this context corresponds to the main site’s deployment, attached to the Git branch you set when the site is created.
[context.production]
  command = "jekyll build"
  [context.production.environment]
    JEKYLL_ENV = "production"

# deploy-preview: this context corresponds to the previews we build for Pull Requests and Merge Requests integrations.
[context.deploy-preview]
  command = "jekyll build --config _config.yml,_config.staging.yml"
  [context.deploy-preview.environment]
    JEKYLL_ENV = "development"

# branch-deploy: this context corresponds to deploys from branches that are not the site’s main production branch.
[context.branch-deploy]
  command = "jekyll build --config _config.yml,_config.staging.yml"
  [context.branch-deploy.environment]
    JEKYLL_ENV = "development"

# redirect to https
[[redirects]]
from = "http://www.edgepointlearning.com/*"
to = "https://www.edgepointlearning.com/:splat"
status = 301
force = true

# redirect to fix infusionsoft link typo to static document
[[redirects]]
from = "/assets/BuildingAStrongFoundationForTrainingWithSolidLearningObjectings.pdf"
to = "/static/BuildingAStrongFoundationForTrainingWithSolidLearningObjectives.pdf"
status = 301
force = false

# redirect to fix old links to static document
[[redirects]]
from = "/assets/EdgePointLearningGeneralInformationBrochure.pdf"
to = "/static/EdgePointLearningGeneralInformationBrochure.pdf"
status = 301
force = false
